networks:
  monitorar:
    driver: bridge

services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: always
    networks:
      - monitorar

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always
    networks:
      - monitorar

volumes:
  prometheus_data:
  grafana_data:
